Boos 319/feature/postgres
intellium-ai/SPA-Flask-React-boilerplate pull request #124
Opened 2021-12-15 17:44 UTC by koutsilisk

In this PR we introduce:
- Posgresql database configuration 
- Some more docker-configuration configuration

Fixes:
- Activate users when population from manage.py
- Email service working from within docker

2021-12-15 17:44 UTC, koutsilisk commented
MERGE AFTER #122

2021-12-16 10:45 UTC, Chichilele requested changes
just add empty lines at the end of each file

2021-12-16 10:45 UTC, Chichilele commented on .gitignore
> +env_files
empty line

2021-12-16 10:45 UTC, Chichilele commented on README.md
> +2. Simply `docker-compose --env-file ./env_files/api.env up` to bring the app up.
Wouldn't it be better to have the files pointed at in the docker-compose file?

2021-12-16 10:45 UTC, Chichilele commented on env_examples/postgres.env
> +FLASK_DATABASE_PASSWORD=flask_api_password
empty line

2021-12-16 10:45 UTC, Chichilele commented on env_examples/api.env
> +FLASK_MAIL_PORT=587
empty line

2021-12-16 10:45 UTC, Chichilele commented on docker-compose.yml
> +  postgres:
empty line

2021-12-16 11:18 UTC, koutsilisk commented on README.md
> +2. Simply `docker-compose --env-file ./env_files/api.env up` to bring the app up.
we have them but in order to expose the mail port and not to have it as a static port i added this, and in docker-compose we have `- ${FLASK_MAIL_PORT}:${FLASK_MAIL_PORT}`. That's the reason. I could make it static ( example 587:587) and add a comment that this is the mail port

2021-12-16 11:19 UTC, Chichilele commented on README.md
> +2. Simply `docker-compose --env-file ./env_files/api.env up` to bring the app up.
that's not exactly what I meant. You can point to a config file directly form the docker-compose file I think? have a look at our config in boost.

2021-12-16 11:21 UTC, Chichilele approved these changes

2021-12-16 11:21 UTC, Chichilele commented on docker-compose.yml
> +
the last line should be enmpty

2021-12-16 11:32 UTC, koutsilisk commented on README.md
> +2. Simply `docker-compose --env-file ./env_files/api.env up` to bring the app up.
in order not to use the --env-file we should have a .env file at the same folder as the docker-compose file as mentioned here: https://docs.docker.com/compose/environment-variables/#the-env-file, the --env-file helps to save the configuration in any folder you want with any name you want

2021-12-16 17:07 UTC, Chichilele approved these changes

2021-12-16 17:07 UTC, Chichilele commented on Makefile
> +	@docker-compose --env-file ./env_files/api.env logs -f
empty line

2021-12-16 17:40 UTC, merged