Boos 363/fix/schemas validators
intellium-ai/SPA-Flask-React-boilerplate pull request #134
Opened 2021-12-22 17:25 UTC by koutsilisk

In this pr we added:
- Roles schema name field validator
- Groups schema name field validator 
- Additional tests for groups/role/users POST/PATCH requests.

2021-12-22 19:55 UTC, Chichilele requested changes

2021-12-22 19:55 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +        name = name.replace(" ", "")
What if the group name is multiple words: `"Blue toes gang"`. It might be better to look for a trimming solution (remove the leading and trailing spaces in the name)

2021-12-22 19:55 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +            raise ValidationError("Field name must contain at least three characters.")
This seems redundant, isn't it? Yes, it's slightly different but you'd have to comply with 3 characters anyway. So better let the user know the requirements right away

2021-12-22 19:55 UTC, Chichilele commented on backend/project/api/schemas/role.py
> +        name = name.replace(" ", "")
Same issue with names with spaces in them. Prefer a trimming strategy

2021-12-22 19:55 UTC, Chichilele commented on backend/project/api/schemas/role.py
> +        if len(name) < 1:
redundant with the following line

2021-12-22 19:55 UTC, Chichilele commented on backend/project/tests/routes/test_users_routes.py
> +                    "Username should only contain letters, numbers and/or the underscore character."
Edit this error message -> "[...] numbers and underscores."

2021-12-23 10:26 UTC, koutsilisk commented on backend/project/api/schemas/group.py
> +        name = name.replace(" ", "")
this is just for validation, the name is saved as its given in the payload .So if the name is  "Blue toes gang" , it the validation will remove whitespaces, ("Bluetoesgang") check if its > 3 characters ,( well it is ) and it will save it as "Blue toes gang".

2022-01-06 11:41 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +        name = name.replace(" ", "")
That's still bad because the check don't reflect the expected checks.

2022-01-06 11:42 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +        name = name.replace(" ", "")
You can use regex also. Name can't start nor end with a space, etc...

2022-01-10 15:12 UTC, closed without merging