Boos 453/feature/redis celery
intellium-ai/SPA-Flask-React-boilerplate pull request #140
Opened 2022-01-11 14:19 UTC by koutsilisk

In this PR we introduce:
- Celery setup.
- Celery docker container.
- Redis docker container.

2022-01-12 17:28 UTC, Chichilele requested changes
create a celery extension

2022-01-12 17:28 UTC, Chichilele commented on backend/.gitignore
> +*.pyc
oh good spot!

2022-01-12 17:28 UTC, Chichilele commented on backend/Dockerfile
> +ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1
can you remind me what was this for? Was it celery or general python stuff?

2022-01-12 17:28 UTC, Chichilele commented on backend/requirements.txt
> +packaging==21.3
careful, we're upgrading an existing dependency (if everything works I suppose it's fine but let's add it to all PRs)

2022-01-12 17:28 UTC, Chichilele commented on docker-compose.yml
> +  redis:
Maybe we can find a high level naming... I'm sorry I can't think of anything right now but to keep in mind. I would have said `broker` but it's more than that... `ram_db`? idk

2022-01-12 17:28 UTC, Chichilele commented on docker-compose.yml
> +      redis:
Let's also watch how many dependencies we add. We may end up with a very sequential startup which means it'll be slow. Some services may require others to work but can be started before their dependencies are READY

2022-01-12 17:28 UTC, Chichilele commented on backend/project/tasks.py
> +@celery.task
How about the test setup for celery functions?

2022-01-12 17:28 UTC, Chichilele commented on backend/project/app.py
> +celery = Celery(
Celery should be in its own module, implementing `XXX.init_app(app, ARGS)`

2022-01-13 09:27 UTC, koutsilisk commented on backend/Dockerfile
> +ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1
This is python stuff, the pythonunbuffered is for logs. I saw them in other dockerfiles so I added them too.

2022-01-13 09:27 UTC, koutsilisk commented on backend/requirements.txt
> +packaging==21.3
this got upgraded when installing celery.

2022-01-13 09:29 UTC, koutsilisk commented on docker-compose.yml
> +      redis:
good point.

2022-01-13 13:21 UTC, Chichilele requested changes

2022-01-13 13:21 UTC, Chichilele commented on backend/project/tasks.py
> +from project.extensions.celery import celery
```python
from project.extensions import celery
```

2022-01-13 13:21 UTC, Chichilele commented on backend/project/extensions/celery.py
> +
Implement extension interface with init_ap() method

2022-01-13 13:41 UTC, Chichilele commented on backend/project/extensions/celery.py
> +
done

2022-01-13 13:41 UTC, Chichilele commented on backend/project/tasks.py
> +from project.extensions.celery import celery
fixed

2022-01-13 17:01 UTC, Chichilele requested changes
- [ ] Since you added a dummy task, add a dummy test
- Are you sure the code you borrowed is fine?

2022-01-13 17:35 UTC, koutsilisk commented on backend/project/extensions/celery.py
> +        self.autodiscover_tasks("project")
the if app in kwargs is in order to be able to init with an app or without and app, ``` celery = FlaskCelery(app) or celery = FlaskCelery() ``` the autodiscover_tasks i saw it from biran capello but checked what it does.,basically it tries to find a task module under the project folder ( in that case )

2022-01-17 12:05 UTC, Chichilele commented
Closing for rebase

2022-01-17 12:06 UTC, closed without merging