Boos 459/feature/users groups
intellium-ai/SPA-Flask-React-boilerplate pull request #151
Opened 2022-01-18 14:29 UTC by koutsilisk

in this PR we introduce:
- User's get_user_groups endpoint implementation.
- id_match decorator to check if JWT payload id matches given id. 
- The idea of [DTOs].(https://en.wikipedia.org/wiki/Data_transfer_object#:~:text=In%20the%20field%20of%20programming,that%20carries%20data%20between%20processes.&text=In%20other%20words%2C%20DTOs%20are,transferring%20data%20over%20the%20wire.) 

Changes
- Refactor all services to use "global" db session and discarded dependency injection as  it was a bad approach for the specific case.

2022-01-18 16:29 UTC, Chichilele requested changes
* Implement DTOs as schemas
*

2022-01-18 16:29 UTC, Chichilele commented on backend/project/tests/services/test_users_service.py
> +        assert 1 == result[1]["roles_count"]
I'm don't understand why we do `result[0]["id"]` and not `result[0].id`? I thought `results` would be a list of data class not a list of dict?

2022-01-18 16:29 UTC, Chichilele commented on backend/project/api/services/users.py
> +                members_count += len(role.users)
* Break down into 2 methods
* Your members_count would count users twice if they have multiple roles with the same group. You can probably break that down into 2 or 3 SQLa queries (1 would be tricky because of the many to many relationship)

2022-01-18 16:29 UTC, Chichilele commented on backend/project/api/services/users.py
> +            groups_insights.append(group_insights_dto.__dict__)
Using `__dict__` looks ugly and breaks the function signature

2022-01-18 22:11 UTC, koutsilisk commented on backend/project/api/services/users.py
> +                members_count += len(role.users)
i need to refresh my sql :/

2022-01-20 10:17 UTC, koutsilisk commented on backend/project/api/services/users.py
> +                members_count += len(role.users)
Updated!

2022-01-20 17:15 UTC, Chichilele requested changes

2022-01-20 17:15 UTC, Chichilele commented on backend/project/api/services/users.py
> +                .count()
with `distinct`?

2022-01-21 13:47 UTC, koutsilisk commented
closing pr to rebase and resolve conflict

2022-01-21 13:47 UTC, closed without merging