Boos 179 swagger ghpages
intellium-ai/SPA-Flask-React-boilerplate pull request #29
Opened 2021-11-04 10:20 UTC by Chichilele

* Refactor openapi docs in `docs` folder
* openAPI docs to GitHub pages: https://intellium-ai.github.io/SPA-Flask-React-boilerplate/ (simple HTML file loading Swagger packages)

2021-11-04 10:23 UTC, koutsilisk commented on docs/index.html
> +        <title>My New API</title>
Intellium boilerplate API or something equivalent

2021-11-04 10:26 UTC, koutsilisk requested changes
Change the html title on index.html to reflect the actual API, My new API is not that helpful.

2021-11-04 10:29 UTC, Chichilele commented
> Change the html title on index.html to reflect the actual API, My new API is not that helpful.

good point, not sure it shows anywhere though

2021-11-04 10:31 UTC, koutsilisk commented
It shows on the tab

2021-11-04 10:33 UTC, koutsilisk approved these changes

2021-11-05 11:05 UTC, Chichilele commented
I'll actually merge this and have @joaopcartier 's review done directly on GH pages and reported on the https://intellium-ai.atlassian.net/browse/BOOS-179?atlOrigin=eyJpIjoiNWQyYjE3NzYxMTA1NDY2Nzk2MTc3MTA3ODgyYTBiYWIiLCJwIjoiaiJ9

2021-11-05 11:06 UTC, merged