Boos 185 read single role
intellium-ai/SPA-Flask-React-boilerplate pull request #39
Opened 2021-11-09 14:39 UTC by anibalgatica

Read single role, read role list updated to use the API endpoint instead of mock data.

2021-11-09 14:40 UTC, joaopcartier approved these changes

2021-11-10 15:32 UTC, joaopcartier approved these changes

2021-11-10 15:34 UTC, joaopcartier requested changes

2021-11-10 15:34 UTC, joaopcartier commented on backend/project/api/routes/roles_routes.py
> +    print(request)
I guess this print was created when we were having problems with connecting with the API.
Don't think it's meaningful to the backend code

2021-11-10 16:03 UTC, koutsilisk commented on frontend/src/components/role/RoleDetails.tsx
> +// }
do we need this commented code ?

2021-11-10 16:08 UTC, koutsilisk requested changes

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/RoleDetails.tsx
> +                // ]}
same

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/RoleDetails.tsx
> +        </div> */}
same

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/RolesList.tsx
> +              // }}
same

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/roleAPI.ts
> +  };
add new line at end of file

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/roleSlice.ts
> +        // })
same for commented code here

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/role/roleSlice.ts
> +  export default roleSlice.reducer
new line

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/components/user/userAPI.ts
> +  const response = await request("http://localhost:5000/api/users");
can http://localhost:5000 be a "global" variable and use something like HOST/api/users ? This way you just update the var in one place and can reuse it everywhere

2021-11-10 16:08 UTC, koutsilisk commented on frontend/src/types/role.ts
> +  }
new line

2021-11-10 17:05 UTC, anibalgatica commented on frontend/src/components/role/roleAPI.ts
> +  };
It doesn't cause any harm, but it's not required in javascript or typescript

2021-11-10 17:07 UTC, anibalgatica commented on frontend/src/components/user/userAPI.ts
> +  const response = await request("http://localhost:5000/api/users");
It's actually a good idea, not necessary to do here I think but I'll take a note to do it later.

2021-11-10 17:28 UTC, merged