Boos 180/feature/user login
intellium-ai/SPA-Flask-React-boilerplate pull request #47
Opened 2021-11-15 15:08 UTC by koutsilisk

In this pr we introduce:

- Flask-jwt-extended package
- Flask-bcrypt package
- Auth blueprint
- Auth service
- Login schema
- login route
- User password field
- User jwt encode/decode functions

2021-11-16 00:16 UTC, Chichilele requested changes
Good PR. See comments and add service test.

2021-11-16 00:16 UTC, Chichilele commented on backend/project/auth/services/auth.py
> +            return None
Let the else be handled by an exception rather than covering the case here (error handling ticket)

2021-11-16 00:16 UTC, Chichilele commented on backend/project/tests/auth/test_auth_routes.py
> +            data={},
👏

2021-11-16 00:16 UTC, Chichilele commented on backend/project/tests/auth/test_auth_routes.py
> +    def test_auth_login_short_password_lenght(self, api_client):
How about checking this only on the creation of the password and returning credential error when attempting to login? Makes it simpler for us and hides the rule to potential attackers

2021-11-16 00:16 UTC, Chichilele commented on backend/project/tests/conftest.py
> +
thanks for commenting that!

2021-11-16 12:12 UTC, koutsilisk commented on backend/project/auth/services/auth.py
> +        if user and bcrypt.check_password_hash(user.password, password):
it could be also implemented in the User class so you don't complicate that many layers and the auth service is not dependent on the user service

2021-11-17 19:31 UTC, Chichilele approved these changes

2021-11-17 19:33 UTC, Chichilele commented on backend/project/auth/routes/auth.py
> +    except Exception:
Pushed changes

2021-11-18 14:01 UTC, merged