Boos 151 groups service
intellium-ai/SPA-Flask-React-boilerplate pull request #61
Opened 2021-11-17 14:28 UTC by Chichilele

-     Add Groups_service with CRUD operations
-     Group schemas has id and timestamp as read-onlu

2021-11-18 11:44 UTC, koutsilisk requested changes
Great naming at the service, really like that 💯

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/models/role.py
> +from project.api.models.user_role import UserRole
from project.api.models import UserRole. I think this is more elegant and clean, we import all the models in the __init__ so we can import like this afterwards.

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/models/user.py
> +from project.api.models.user_role import UserRole
same

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/models/user_role.py
> +from project.api.models.mixins import TimestampMixin
this is fine if we have a mixin file for multiple mixins

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/schemas/group.py
> +        # exclude = ("confirmed_at", "created_at", "updated_at")
i think we can delete this comment

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/services/groups.py
> +            query_result = self._update_model(group_id, **kwargs)
since we query and get the object from the db, is there an advantage to this update approach?

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/services/groups.py
> +        result = self.db_session.query(Group).filter_by(id=group_id).update(kwargs)
Group.query.filter_by(id=group_id).update(kwargs) just in order to be more consistent with the rest of the code

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/api/services/users.py
> +from project.api.services.utils import Utils
from project.api.services import Utils

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/schemas/test_group_schema.py
> -            "updated_at": "2021-10-27T12:08:39",
why we deleted those fields?

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert result == db_state
🔥

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +    def test_Groups_service_get_all_empty_table(self, setUp, mocker):
isn' that tested from the previous test ? with the parametrize

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert None == result
assert not result

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert group == result
you really see things from the opposite perspective, haha, maybe assert result == group to keep it the same as all the other tests

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert None == result
assert not result

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert group == result
reverse

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert None == result
same

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert False == result
assert not result, or reverse

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert "Group name already exist" == result
same

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert "Invalid Payload" == result
same

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert False == result
same

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_groups_service.py
> +        assert True == result
assert result or reverse

2021-11-18 11:44 UTC, koutsilisk commented on backend/project/tests/services/test_roles_service.py
> +        assert [] == result
why this change ?

2021-11-18 18:35 UTC, Chichilele commented on backend/project/api/models/user_role.py
> +from project.api.models.mixins import TimestampMixin
add to ini file

2021-11-18 18:37 UTC, Chichilele commented on backend/project/api/services/groups.py
> +            query_result = self._update_model(group_id, **kwargs)
consistency. the dict lookup is a hack

2021-11-18 18:38 UTC, Chichilele commented on backend/project/tests/schemas/test_group_schema.py
> -            "updated_at": "2021-10-27T12:08:39",
Not deserialisable (read only)

2021-11-18 18:39 UTC, Chichilele commented on backend/project/tests/services/test_groups_service.py
> +        assert None == result
Prefer it this way because it's clear to the reader it's a `None` not a `False`

2021-11-18 18:41 UTC, Chichilele commented on backend/project/tests/services/test_groups_service.py
> +        assert group == result
Haha yes. I just try to do "static value" == variable usually and it comes from there haha. It's a trick to avoid getting stuck with the typo `variable = "Static value"` because the transaction returns although it's not a check

2021-11-18 18:45 UTC, Chichilele commented on backend/project/tests/services/test_roles_service.py
> +        assert [] == result
explicit

2021-11-18 19:02 UTC, Chichilele commented on backend/project/api/models/role.py
> +from project.api.models.user_role import UserRole
circular imports issue (which sounds obvious now I think about it: when `__init__` imports `Role` it'll import the `Mixin` from __init__ itself which will import `Role` again. We should stick either to `.user_role` or `project.api.models.user_role`

2021-11-18 19:13 UTC, Chichilele commented on backend/project/api/models/role.py
> +from project.api.models.user_role import UserRole
Flask uses mostly `from .submodule import object` and django uses `from django.submodule import object`

2021-11-18 20:11 UTC, Chichilele commented on backend/project/api/services/groups.py
> +        result = self.db_session.query(Group).filter_by(id=group_id).update(kwargs)
It doesn't work exactly the same way. I'll have to investigate

2021-11-19 09:24 UTC, koutsilisk commented on backend/project/api/models/role.py
> +from project.api.models.user_role import UserRole
ok then probably keep the full path in order to be explicit, I am fine with both options

2021-11-19 09:28 UTC, koutsilisk approved these changes

2021-11-19 15:16 UTC, Chichilele commented on backend/project/api/models/role.py
> +from project.api.models.user_role import UserRole
Found a fix see incoming commits

2021-11-19 16:13 UTC, Chichilele commented on backend/project/api/services/groups.py
> +        result = self.db_session.query(Group).filter_by(id=group_id).update(kwargs)
Ok fixed the tests now it seems to be working !

2021-11-19 16:26 UTC, koutsilisk approved these changes

2021-11-19 16:26 UTC, Chichilele commented on backend/project/tests/services/test_groups_service.py
> +    def test_Groups_service_get_all_empty_table(self, setUp, mocker):
yes removed

2021-11-19 16:27 UTC, merged