Boos 217 add group to role
intellium-ai/SPA-Flask-React-boilerplate pull request #83
Opened 2021-11-25 20:25 UTC by Chichilele

## Merge PR #81 before merging this PR #83
Add a one-to-many relationship between groups and roles tables
* add `group` fields to `Role` model
* add logic to `Role` model constructor: supports types `int` and `Group` (respectively `group.id` and `Group` model instance)
* update `RoleSchema` deserializer to return the `group_id` 
* update Roles_service to work  with `group_id`
* reset migration folder

2021-11-26 11:31 UTC, koutsilisk requested changes

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/api/routes/roles_routes.py
>          updated_User = roles_service.update(role_id, **patch_data)
oops, copy paste typo, thats on me

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/api/schemas/group.py
> +        exclude = ("roles",)
so we are not serializing the roles?

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/api/schemas/role.py
> +                    Group.query.filter_by(name=data["group"]["name"]).one().id
maybe use the Service layer here to keep it more abstract

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/tests/routes/test_roles_routes.py
> +logger = logging.getLogger(__name__)
why do we need a logger for the tests ?

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/tests/routes/test_roles_routes.py
> +        assert "Invalid payload".lower() in data["error"].lower()
i don't like the lower here, imagine we send a response like , "inVALiD payLOAD", the test will pass

2021-11-26 11:31 UTC, koutsilisk commented on backend/project/tests/schemas/test_role_schema.py
> +    def deserialized_role(self):
didn't we change that to Role_json and Role_details_json?

2021-11-26 11:31 UTC, koutsilisk commented on docker-compose.yml
> +    stop_signal: SIGINT
☑️

2021-11-26 17:14 UTC, Chichilele commented on backend/migrations/env.py
> +        url=url, target_metadata=target_metadata, literal_binds=True
Good spot thanks (I would have never checked migration files!)

2021-11-26 17:16 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +        exclude = ("roles",)
I struggled os much around roles.group thatI forgot this. Maybe I need to write much more stuff than I thought. Should we return user.roles list too?

2021-11-26 17:17 UTC, Chichilele commented on backend/project/api/schemas/role.py
> +                    Group.query.filter_by(name=data["group"]["name"]).one().id
I chose to write it here so that if the group doesn't exist the serialization fails? It's a nice way to control things both in `POST` and `UPDATE`

2021-11-26 17:18 UTC, Chichilele commented on backend/project/tests/routes/test_roles_routes.py
> +        assert "Invalid payload".lower() in data["error"].lower()
Ok

2021-11-26 17:34 UTC, Chichilele commented on backend/project/tests/schemas/test_role_schema.py
> +    def deserialized_role(self):
probably not everywhere...?

2021-11-29 09:53 UTC, koutsilisk commented on backend/project/api/schemas/group.py
> +        exclude = ("roles",)
I think we should. Maybe we should have a frontend opinion. @anibalgatica do you think you need the groups roles when you fetch a group ?

2021-11-29 09:54 UTC, koutsilisk commented on backend/project/api/schemas/role.py
> +                    Group.query.filter_by(name=data["group"]["name"]).one().id
i mean instead of Group.query.filter_by(name=data["group"]["name"]).one().id, use service.get_by_name(data["group"]["name"]).id

2021-11-29 10:28 UTC, anibalgatica commented on backend/project/api/schemas/group.py
> +        exclude = ("roles",)
I agree, we should get user.roles, basically we should get in the API call all that we want to display in a single view

2021-11-29 10:51 UTC, Chichilele commented on backend/project/api/schemas/group.py
> +        exclude = ("roles",)
Agreed. I'll add a separate ticket for that though, as there might be a bit of work, especially around testing. Another ticket will be added for the contract update.

2021-11-29 10:57 UTC, koutsilisk approved these changes

2021-11-29 11:08 UTC, merged